# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='fare',
        ),
        migrations.AddField(
            model_name='orders',
            name='addr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
