# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20170518_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uPassword',
            field=models.CharField(max_length=64),
        ),
    ]
