# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170518_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsort',
            name='sortClass',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
